# Generated by Django 2.0.13 on 2019-03-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('word', models.CharField(max_length=30)),
                ('definition', models.CharField(max_length=200)),
                ('word_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
