# Generated by Django 2.0.13 on 2019-03-07 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_wordtype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WordType',
            new_name='List',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='word_type',
            new_name='list_type',
        ),
    ]
