# Generated by Django 2.0.13 on 2019-03-11 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice2', to='study.WordList')),
                ('choice3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice3', to='study.WordList')),
                ('choice4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice4', to='study.WordList')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='study.WordList')),
                ('user_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_response', to='study.WordList')),
            ],
        ),
    ]
