# Generated by Django 2.0.13 on 2019-03-24 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
        ('testmode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice4',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer', to='study.WordList'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_response', to='study.WordList'),
        ),
        migrations.AddField(
            model_name='choices',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='testmode.Question'),
        ),
        migrations.AddField(
            model_name='choices',
            name='choice_val',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.WordList'),
        ),
    ]
