# Generated by Django 2.0.13 on 2019-03-09 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TestsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.IntegerField(default=1)),
                ('right', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.WordList')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='tests',
            name='test_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.TestsData'),
        ),
    ]
